version: "2.2"
services:
  jobmanager:
    image: flink-quickstart:latest
    ports:
      - "8081:8081"
    command: standalone-job --job-classname org.myorg.quickstart.DataStreamJob --jars /opt/flink/usrlib/artifacts/quickstart-0.1.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2

  taskmanager:
    image: flink-quickstart:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
