openapi: 3.0.3
info:
  title: Assignment Service API
servers:
  - url: http://localhost:8082
tags:
  - name: Assignments
paths:
  /api/assignments/{user_id}:
    get:
      tags:
        - Assignments
      summary: Get experiment assignments for a user
      description: >
        Retrieves the list of active experiments and their assigned variants for
        a given user.
      operationId: getExperimentsAndVariantsForUser
      parameters:
        - name: user_id
          in: path
          required: true
          description: The unique identifier for the user
          schema:
            type: string
          example: user_12345
      responses:
        '200':
          description: Successfully retrieved experiment assignments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: >-
                    #/components/schemas/GetExperimentsAndVariantsForBucketResponse
              examples:
                singleExperiment:
                  summary: Single active experiment for user's bucket
                  value:
                    feature_flag_1: variant_a
                multipleExperiments:
                  summary: Multiple active experiments for user's bucket
                  value:
                    feature_flag_1: variant_a
                    feature_flag_2: variant_b
                emptyResponse:
                  summary: No active experiments for user's bucket
                  value: {}
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    GetExperimentsAndVariantsForBucketResponse:
      type: object
      additionalProperties:
        type: string
      description: Map of feature flag IDs to variant IDs
    Violation:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
    ProblemDetail:
      type: object
      properties:
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        violations:
          type: array
          items:
            $ref: '#/components/schemas/Violation'
  responses:
    BadRequest:
      description: Bad request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            title: Bad Request
            status: 400
            detail: Request body is required
    InternalServerError:
      description: Internal server error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            title: Internal Server Error
            status: 500
            detail: An unexpected error occurred
