openapi: 3.0.3
info:
  title: Admin Service API
servers:
  - url: http://localhost:8081/api
tags:
  - name: Event Catalog
paths:
  /events-catalog:
    get:
      tags:
        - Event Catalog
      summary: List or search event types
      operationId: getEventTypes
      parameters:
        - name: search
          in: query
          required: false
          description: Optional search term to find eventTypes by name
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventType'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Event Catalog
      summary: Create an event type
      operationId: createEventType
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventTypeRequest'
            example:
              name: Purchase Completed
              eventKey: purchase_completed
              description: >-
                Fired when a user completes a purchase. This example maps to the
                object: { "order_total": 100.0, "currency": "USD" }
              fields:
                - name: Order Total
                  fieldKey: order_total
                  dataType: float
                - name: Currency
                  fieldKey: currency
                  dataType: string
      responses:
        '201':
          description: Event type created successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /events-catalog/{eventTypeId}:
    get:
      tags:
        - Event Catalog
      summary: Get an event type by ID
      operationId: getEventType
      parameters:
        - $ref: '#/components/parameters/eventTypeId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventType'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: Event type not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
              example:
                title: Not Found
                status: 404
                detail: Event type not found
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - Event Catalog
      summary: Delete an event type
      description: Deletes the event type and all associated fields.
      operationId: deleteEventType
      parameters:
        - $ref: '#/components/parameters/eventTypeId'
      responses:
        '204':
          description: Event type deleted successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /events-catalog/event-key-available:
    get:
      tags:
        - Event Catalog
      summary: Check if an event key is available
      operationId: isEventKeyAvailableForExperiment
      parameters:
        - name: eventKey
          in: query
          required: true
          schema:
            type: string
          example: purchase_completed
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean
              example:
                available: true
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /events-catalog/{eventTypeId}/field-key-available:
    get:
      tags:
        - Event Catalog
      summary: Check if a field key is available
      operationId: isFieldKeyAvailableForExperiment
      parameters:
        - $ref: '#/components/parameters/eventTypeId'
        - name: fieldKey
          in: query
          required: true
          schema:
            type: string
          example: order_total
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean
              example:
                available: true
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  parameters:
    eventTypeId:
      name: eventTypeId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      example: 989618ba-efce-4854-be23-ede08787a6d1
  schemas:
    CreateEventTypeRequest:
      type: object
      required:
        - name
        - eventKey
        - fields
      properties:
        name:
          type: string
          maxLength: 100
          example: Purchase Completed
        eventKey:
          type: string
          maxLength: 50
          pattern: ^[a-zA-Z][a-zA-Z0-9_-]*$
          example: purchase_completed
        description:
          type: string
          example: Fired when a user completes a purchase
        fields:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/EventFieldRequest'
    EventFieldRequest:
      type: object
      required:
        - name
        - fieldKey
        - dataType
      properties:
        name:
          type: string
          maxLength: 100
          example: Order Total
        fieldKey:
          type: string
          maxLength: 50
          pattern: ^[a-zA-Z][a-zA-Z0-9_-]*$
          example: order_total
        dataType:
          $ref: '#/components/schemas/DataType'
    EventType:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 989618ba-efce-4854-be23-ede08787a6d1
        name:
          type: string
        eventKey:
          type: string
        version:
          type: integer
        description:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        fields:
          type: array
          items:
            $ref: '#/components/schemas/EventField'
    EventField:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 250bf027-d8d9-436d-ba21-57f46162c1b0
        name:
          type: string
        fieldKey:
          type: string
        dataType:
          $ref: '#/components/schemas/DataType'
    DataType:
      type: string
      enum:
        - string
        - int
        - float
        - boolean
        - timestamp
    Violation:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
    ProblemDetail:
      type: object
      properties:
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        violations:
          type: array
          items:
            $ref: '#/components/schemas/Violation'
  responses:
    InternalServerError:
      description: Internal server error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            title: Internal Server Error
            status: 500
            detail: An unexpected error occurred
    BadRequest:
      description: Bad request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            title: Bad Request
            status: 400
            detail: Request body is required
    ValidationError:
      description: Validation error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            title: Validation Error
            status: 422
            detail: One or more fields failed validation
            violations:
              - field: name
                message: Name is required
