// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events_catalog/v1/events_catalog.proto
// Protobuf Java Version: 4.33.4

package org.prism.eventsservice.grpc.events_catalog.v1;

/**
 * Protobuf enum {@code events_catalog.v1.DataType}
 */
@com.google.protobuf.Generated
public enum DataType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DATA_TYPE_UNSPECIFIED = 0;</code>
   */
  DATA_TYPE_UNSPECIFIED(0),
  /**
   * <code>DATA_TYPE_STRING = 1;</code>
   */
  DATA_TYPE_STRING(1),
  /**
   * <code>DATA_TYPE_INT = 2;</code>
   */
  DATA_TYPE_INT(2),
  /**
   * <code>DATA_TYPE_FLOAT = 3;</code>
   */
  DATA_TYPE_FLOAT(3),
  /**
   * <code>DATA_TYPE_BOOL = 4;</code>
   */
  DATA_TYPE_BOOL(4),
  /**
   * <code>DATA_TYPE_TIMESTAMP = 5;</code>
   */
  DATA_TYPE_TIMESTAMP(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "DataType");
  }
  /**
   * <code>DATA_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int DATA_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>DATA_TYPE_STRING = 1;</code>
   */
  public static final int DATA_TYPE_STRING_VALUE = 1;
  /**
   * <code>DATA_TYPE_INT = 2;</code>
   */
  public static final int DATA_TYPE_INT_VALUE = 2;
  /**
   * <code>DATA_TYPE_FLOAT = 3;</code>
   */
  public static final int DATA_TYPE_FLOAT_VALUE = 3;
  /**
   * <code>DATA_TYPE_BOOL = 4;</code>
   */
  public static final int DATA_TYPE_BOOL_VALUE = 4;
  /**
   * <code>DATA_TYPE_TIMESTAMP = 5;</code>
   */
  public static final int DATA_TYPE_TIMESTAMP_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DataType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DataType forNumber(int value) {
    switch (value) {
      case 0: return DATA_TYPE_UNSPECIFIED;
      case 1: return DATA_TYPE_STRING;
      case 2: return DATA_TYPE_INT;
      case 3: return DATA_TYPE_FLOAT;
      case 4: return DATA_TYPE_BOOL;
      case 5: return DATA_TYPE_TIMESTAMP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DataType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DataType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
          public DataType findValueByNumber(int number) {
            return DataType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.getDescriptor().getEnumTypes().get(0);
  }

  private static final DataType[] VALUES = values();

  public static DataType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DataType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:events_catalog.v1.DataType)
}

