// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events_catalog/v1/events_catalog.proto
// Protobuf Java Version: 4.33.4

package org.prism.eventsservice.grpc.events_catalog.v1;

@com.google.protobuf.Generated
public interface EventTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_catalog.v1.EventType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string event_key = 3;</code>
   * @return The eventKey.
   */
  java.lang.String getEventKey();
  /**
   * <code>string event_key = 3;</code>
   * @return The bytes for eventKey.
   */
  com.google.protobuf.ByteString
      getEventKeyBytes();

  /**
   * <code>int32 version = 4;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>optional string description = 5;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 5;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 5;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>repeated .events_catalog.v1.EventField fields = 7;</code>
   */
  java.util.List<org.prism.eventsservice.grpc.events_catalog.v1.EventField> 
      getFieldsList();
  /**
   * <code>repeated .events_catalog.v1.EventField fields = 7;</code>
   */
  org.prism.eventsservice.grpc.events_catalog.v1.EventField getFields(int index);
  /**
   * <code>repeated .events_catalog.v1.EventField fields = 7;</code>
   */
  int getFieldsCount();
  /**
   * <code>repeated .events_catalog.v1.EventField fields = 7;</code>
   */
  java.util.List<? extends org.prism.eventsservice.grpc.events_catalog.v1.EventFieldOrBuilder> 
      getFieldsOrBuilderList();
  /**
   * <code>repeated .events_catalog.v1.EventField fields = 7;</code>
   */
  org.prism.eventsservice.grpc.events_catalog.v1.EventFieldOrBuilder getFieldsOrBuilder(
      int index);
}
