// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events_catalog/v1/events_catalog.proto
// Protobuf Java Version: 4.33.4

package org.prism.eventsservice.grpc.events_catalog.v1;

@com.google.protobuf.Generated
public interface EventFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_catalog.v1.EventField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string event_type_id = 2;</code>
   * @return The eventTypeId.
   */
  java.lang.String getEventTypeId();
  /**
   * <code>string event_type_id = 2;</code>
   * @return The bytes for eventTypeId.
   */
  com.google.protobuf.ByteString
      getEventTypeIdBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string field_key = 4;</code>
   * @return The fieldKey.
   */
  java.lang.String getFieldKey();
  /**
   * <code>string field_key = 4;</code>
   * @return The bytes for fieldKey.
   */
  com.google.protobuf.ByteString
      getFieldKeyBytes();

  /**
   * <code>.events_catalog.v1.DataType data_type = 5;</code>
   * @return The enum numeric value on the wire for dataType.
   */
  int getDataTypeValue();
  /**
   * <code>.events_catalog.v1.DataType data_type = 5;</code>
   * @return The dataType.
   */
  org.prism.eventsservice.grpc.events_catalog.v1.DataType getDataType();
}
