// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events_catalog/v1/events_catalog.proto
// Protobuf Java Version: 4.33.4

package org.prism.eventsservice.grpc.events_catalog.v1;

/**
 * Protobuf type {@code events_catalog.v1.EventField}
 */
@com.google.protobuf.Generated
public final class EventField extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:events_catalog.v1.EventField)
    EventFieldOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "EventField");
  }
  // Use EventField.newBuilder() to construct.
  private EventField(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EventField() {
    id_ = "";
    eventTypeId_ = "";
    name_ = "";
    fieldKey_ = "";
    dataType_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_EventField_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_EventField_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.prism.eventsservice.grpc.events_catalog.v1.EventField.class, org.prism.eventsservice.grpc.events_catalog.v1.EventField.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_TYPE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventTypeId_ = "";
  /**
   * <code>string event_type_id = 2;</code>
   * @return The eventTypeId.
   */
  @java.lang.Override
  public java.lang.String getEventTypeId() {
    java.lang.Object ref = eventTypeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventTypeId_ = s;
      return s;
    }
  }
  /**
   * <code>string event_type_id = 2;</code>
   * @return The bytes for eventTypeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTypeIdBytes() {
    java.lang.Object ref = eventTypeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventTypeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD_KEY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fieldKey_ = "";
  /**
   * <code>string field_key = 4;</code>
   * @return The fieldKey.
   */
  @java.lang.Override
  public java.lang.String getFieldKey() {
    java.lang.Object ref = fieldKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fieldKey_ = s;
      return s;
    }
  }
  /**
   * <code>string field_key = 4;</code>
   * @return The bytes for fieldKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFieldKeyBytes() {
    java.lang.Object ref = fieldKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fieldKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_TYPE_FIELD_NUMBER = 5;
  private int dataType_ = 0;
  /**
   * <code>.events_catalog.v1.DataType data_type = 5;</code>
   * @return The enum numeric value on the wire for dataType.
   */
  @java.lang.Override public int getDataTypeValue() {
    return dataType_;
  }
  /**
   * <code>.events_catalog.v1.DataType data_type = 5;</code>
   * @return The dataType.
   */
  @java.lang.Override public org.prism.eventsservice.grpc.events_catalog.v1.DataType getDataType() {
    org.prism.eventsservice.grpc.events_catalog.v1.DataType result = org.prism.eventsservice.grpc.events_catalog.v1.DataType.forNumber(dataType_);
    return result == null ? org.prism.eventsservice.grpc.events_catalog.v1.DataType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventTypeId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, eventTypeId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fieldKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, fieldKey_);
    }
    if (dataType_ != org.prism.eventsservice.grpc.events_catalog.v1.DataType.DATA_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, dataType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventTypeId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, eventTypeId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fieldKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, fieldKey_);
    }
    if (dataType_ != org.prism.eventsservice.grpc.events_catalog.v1.DataType.DATA_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, dataType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.prism.eventsservice.grpc.events_catalog.v1.EventField)) {
      return super.equals(obj);
    }
    org.prism.eventsservice.grpc.events_catalog.v1.EventField other = (org.prism.eventsservice.grpc.events_catalog.v1.EventField) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getEventTypeId()
        .equals(other.getEventTypeId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getFieldKey()
        .equals(other.getFieldKey())) return false;
    if (dataType_ != other.dataType_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + EVENT_TYPE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEventTypeId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + FIELD_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getFieldKey().hashCode();
    hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + dataType_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.prism.eventsservice.grpc.events_catalog.v1.EventField prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code events_catalog.v1.EventField}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:events_catalog.v1.EventField)
      org.prism.eventsservice.grpc.events_catalog.v1.EventFieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_EventField_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_EventField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.prism.eventsservice.grpc.events_catalog.v1.EventField.class, org.prism.eventsservice.grpc.events_catalog.v1.EventField.Builder.class);
    }

    // Construct using org.prism.eventsservice.grpc.events_catalog.v1.EventField.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      eventTypeId_ = "";
      name_ = "";
      fieldKey_ = "";
      dataType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_EventField_descriptor;
    }

    @java.lang.Override
    public org.prism.eventsservice.grpc.events_catalog.v1.EventField getDefaultInstanceForType() {
      return org.prism.eventsservice.grpc.events_catalog.v1.EventField.getDefaultInstance();
    }

    @java.lang.Override
    public org.prism.eventsservice.grpc.events_catalog.v1.EventField build() {
      org.prism.eventsservice.grpc.events_catalog.v1.EventField result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.prism.eventsservice.grpc.events_catalog.v1.EventField buildPartial() {
      org.prism.eventsservice.grpc.events_catalog.v1.EventField result = new org.prism.eventsservice.grpc.events_catalog.v1.EventField(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.prism.eventsservice.grpc.events_catalog.v1.EventField result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.eventTypeId_ = eventTypeId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.fieldKey_ = fieldKey_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.dataType_ = dataType_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.prism.eventsservice.grpc.events_catalog.v1.EventField) {
        return mergeFrom((org.prism.eventsservice.grpc.events_catalog.v1.EventField)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.prism.eventsservice.grpc.events_catalog.v1.EventField other) {
      if (other == org.prism.eventsservice.grpc.events_catalog.v1.EventField.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getEventTypeId().isEmpty()) {
        eventTypeId_ = other.eventTypeId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getFieldKey().isEmpty()) {
        fieldKey_ = other.fieldKey_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.dataType_ != 0) {
        setDataTypeValue(other.getDataTypeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              eventTypeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              fieldKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              dataType_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object eventTypeId_ = "";
    /**
     * <code>string event_type_id = 2;</code>
     * @return The eventTypeId.
     */
    public java.lang.String getEventTypeId() {
      java.lang.Object ref = eventTypeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventTypeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_type_id = 2;</code>
     * @return The bytes for eventTypeId.
     */
    public com.google.protobuf.ByteString
        getEventTypeIdBytes() {
      java.lang.Object ref = eventTypeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventTypeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_type_id = 2;</code>
     * @param value The eventTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventTypeId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string event_type_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventTypeId() {
      eventTypeId_ = getDefaultInstance().getEventTypeId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string event_type_id = 2;</code>
     * @param value The bytes for eventTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventTypeId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object fieldKey_ = "";
    /**
     * <code>string field_key = 4;</code>
     * @return The fieldKey.
     */
    public java.lang.String getFieldKey() {
      java.lang.Object ref = fieldKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field_key = 4;</code>
     * @return The bytes for fieldKey.
     */
    public com.google.protobuf.ByteString
        getFieldKeyBytes() {
      java.lang.Object ref = fieldKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field_key = 4;</code>
     * @param value The fieldKey to set.
     * @return This builder for chaining.
     */
    public Builder setFieldKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fieldKey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string field_key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFieldKey() {
      fieldKey_ = getDefaultInstance().getFieldKey();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string field_key = 4;</code>
     * @param value The bytes for fieldKey to set.
     * @return This builder for chaining.
     */
    public Builder setFieldKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fieldKey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int dataType_ = 0;
    /**
     * <code>.events_catalog.v1.DataType data_type = 5;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.events_catalog.v1.DataType data_type = 5;</code>
     * @param value The enum numeric value on the wire for dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataTypeValue(int value) {
      dataType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.events_catalog.v1.DataType data_type = 5;</code>
     * @return The dataType.
     */
    @java.lang.Override
    public org.prism.eventsservice.grpc.events_catalog.v1.DataType getDataType() {
      org.prism.eventsservice.grpc.events_catalog.v1.DataType result = org.prism.eventsservice.grpc.events_catalog.v1.DataType.forNumber(dataType_);
      return result == null ? org.prism.eventsservice.grpc.events_catalog.v1.DataType.UNRECOGNIZED : result;
    }
    /**
     * <code>.events_catalog.v1.DataType data_type = 5;</code>
     * @param value The dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataType(org.prism.eventsservice.grpc.events_catalog.v1.DataType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000010;
      dataType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.events_catalog.v1.DataType data_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      dataType_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:events_catalog.v1.EventField)
  }

  // @@protoc_insertion_point(class_scope:events_catalog.v1.EventField)
  private static final org.prism.eventsservice.grpc.events_catalog.v1.EventField DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.prism.eventsservice.grpc.events_catalog.v1.EventField();
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.EventField getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventField>
      PARSER = new com.google.protobuf.AbstractParser<EventField>() {
    @java.lang.Override
    public EventField parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EventField> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventField> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.prism.eventsservice.grpc.events_catalog.v1.EventField getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

