// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events_catalog/v1/events_catalog.proto
// Protobuf Java Version: 4.33.4

package org.prism.eventsservice.grpc.events_catalog.v1;

@com.google.protobuf.Generated
public final class EventsCatalog extends com.google.protobuf.GeneratedFile {
  private EventsCatalog() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "EventsCatalog");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_catalog_v1_GetEventTypeByKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_events_catalog_v1_GetEventTypeByKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_catalog_v1_GetEventTypeByKeyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_events_catalog_v1_GetEventTypeByKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_catalog_v1_EventType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_events_catalog_v1_EventType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_catalog_v1_EventField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_events_catalog_v1_EventField_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&events_catalog/v1/events_catalog.proto" +
      "\022\021events_catalog.v1\032\037google/protobuf/tim" +
      "estamp.proto\"-\n\030GetEventTypeByKeyRequest" +
      "\022\021\n\tevent_key\030\001 \001(\t\"a\n\031GetEventTypeByKey" +
      "Response\0225\n\nevent_type\030\001 \001(\0132\034.events_ca" +
      "talog.v1.EventTypeH\000\210\001\001B\r\n\013_event_type\"\322" +
      "\001\n\tEventType\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\021" +
      "\n\tevent_key\030\003 \001(\t\022\017\n\007version\030\004 \001(\005\022\030\n\013de" +
      "scription\030\005 \001(\tH\000\210\001\001\022.\n\ncreated_at\030\006 \001(\013" +
      "2\032.google.protobuf.Timestamp\022-\n\006fields\030\007" +
      " \003(\0132\035.events_catalog.v1.EventFieldB\016\n\014_" +
      "description\"\200\001\n\nEventField\022\n\n\002id\030\001 \001(\t\022\025" +
      "\n\revent_type_id\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\021\n\tf" +
      "ield_key\030\004 \001(\t\022.\n\tdata_type\030\005 \001(\0162\033.even" +
      "ts_catalog.v1.DataType*\220\001\n\010DataType\022\031\n\025D" +
      "ATA_TYPE_UNSPECIFIED\020\000\022\024\n\020DATA_TYPE_STRI" +
      "NG\020\001\022\021\n\rDATA_TYPE_INT\020\002\022\023\n\017DATA_TYPE_FLO" +
      "AT\020\003\022\022\n\016DATA_TYPE_BOOL\020\004\022\027\n\023DATA_TYPE_TI" +
      "MESTAMP\020\0052\206\001\n\024EventsCatalogService\022n\n\021Ge" +
      "tEventTypeByKey\022+.events_catalog.v1.GetE" +
      "ventTypeByKeyRequest\032,.events_catalog.v1" +
      ".GetEventTypeByKeyResponseB\204\001\n.org.prism" +
      ".eventsservice.grpc.events_catalog.v1P\001Z" +
      "Pexperimentation-service/internal/grpc/g" +
      "enerated/events_catalog/v1;events_catalo" +
      "gb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_events_catalog_v1_GetEventTypeByKeyRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_events_catalog_v1_GetEventTypeByKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_events_catalog_v1_GetEventTypeByKeyRequest_descriptor,
        new java.lang.String[] { "EventKey", });
    internal_static_events_catalog_v1_GetEventTypeByKeyResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_events_catalog_v1_GetEventTypeByKeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_events_catalog_v1_GetEventTypeByKeyResponse_descriptor,
        new java.lang.String[] { "EventType", });
    internal_static_events_catalog_v1_EventType_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_events_catalog_v1_EventType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_events_catalog_v1_EventType_descriptor,
        new java.lang.String[] { "Id", "Name", "EventKey", "Version", "Description", "CreatedAt", "Fields", });
    internal_static_events_catalog_v1_EventField_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_events_catalog_v1_EventField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_events_catalog_v1_EventField_descriptor,
        new java.lang.String[] { "Id", "EventTypeId", "Name", "FieldKey", "DataType", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
