// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events_catalog/v1/events_catalog.proto
// Protobuf Java Version: 4.33.4

package org.prism.eventsservice.grpc.events_catalog.v1;

/**
 * Protobuf type {@code events_catalog.v1.GetEventTypeByKeyRequest}
 */
@com.google.protobuf.Generated
public final class GetEventTypeByKeyRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:events_catalog.v1.GetEventTypeByKeyRequest)
    GetEventTypeByKeyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "GetEventTypeByKeyRequest");
  }
  // Use GetEventTypeByKeyRequest.newBuilder() to construct.
  private GetEventTypeByKeyRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetEventTypeByKeyRequest() {
    eventKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_GetEventTypeByKeyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_GetEventTypeByKeyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest.class, org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest.Builder.class);
  }

  public static final int EVENT_KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventKey_ = "";
  /**
   * <code>string event_key = 1;</code>
   * @return The eventKey.
   */
  @java.lang.Override
  public java.lang.String getEventKey() {
    java.lang.Object ref = eventKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventKey_ = s;
      return s;
    }
  }
  /**
   * <code>string event_key = 1;</code>
   * @return The bytes for eventKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventKeyBytes() {
    java.lang.Object ref = eventKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, eventKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, eventKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest)) {
      return super.equals(obj);
    }
    org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest other = (org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest) obj;

    if (!getEventKey()
        .equals(other.getEventKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getEventKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code events_catalog.v1.GetEventTypeByKeyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:events_catalog.v1.GetEventTypeByKeyRequest)
      org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_GetEventTypeByKeyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_GetEventTypeByKeyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest.class, org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest.Builder.class);
    }

    // Construct using org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_GetEventTypeByKeyRequest_descriptor;
    }

    @java.lang.Override
    public org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest getDefaultInstanceForType() {
      return org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest build() {
      org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest buildPartial() {
      org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest result = new org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventKey_ = eventKey_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest) {
        return mergeFrom((org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest other) {
      if (other == org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest.getDefaultInstance()) return this;
      if (!other.getEventKey().isEmpty()) {
        eventKey_ = other.eventKey_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object eventKey_ = "";
    /**
     * <code>string event_key = 1;</code>
     * @return The eventKey.
     */
    public java.lang.String getEventKey() {
      java.lang.Object ref = eventKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_key = 1;</code>
     * @return The bytes for eventKey.
     */
    public com.google.protobuf.ByteString
        getEventKeyBytes() {
      java.lang.Object ref = eventKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_key = 1;</code>
     * @param value The eventKey to set.
     * @return This builder for chaining.
     */
    public Builder setEventKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string event_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventKey() {
      eventKey_ = getDefaultInstance().getEventKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string event_key = 1;</code>
     * @param value The bytes for eventKey to set.
     * @return This builder for chaining.
     */
    public Builder setEventKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:events_catalog.v1.GetEventTypeByKeyRequest)
  }

  // @@protoc_insertion_point(class_scope:events_catalog.v1.GetEventTypeByKeyRequest)
  private static final org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest();
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetEventTypeByKeyRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetEventTypeByKeyRequest>() {
    @java.lang.Override
    public GetEventTypeByKeyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetEventTypeByKeyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetEventTypeByKeyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

