// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events_catalog/v1/events_catalog.proto
// Protobuf Java Version: 4.33.4

package org.prism.eventsservice.grpc.events_catalog.v1;

@com.google.protobuf.Generated
public interface GetEventTypeByKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_catalog.v1.GetEventTypeByKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_key = 1;</code>
   * @return The eventKey.
   */
  java.lang.String getEventKey();
  /**
   * <code>string event_key = 1;</code>
   * @return The bytes for eventKey.
   */
  com.google.protobuf.ByteString
      getEventKeyBytes();
}
