// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events_catalog/v1/events_catalog.proto
// Protobuf Java Version: 4.33.4

package org.prism.eventsservice.grpc.events_catalog.v1;

/**
 * Protobuf type {@code events_catalog.v1.GetEventTypeByKeyResponse}
 */
@com.google.protobuf.Generated
public final class GetEventTypeByKeyResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:events_catalog.v1.GetEventTypeByKeyResponse)
    GetEventTypeByKeyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "GetEventTypeByKeyResponse");
  }
  // Use GetEventTypeByKeyResponse.newBuilder() to construct.
  private GetEventTypeByKeyResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetEventTypeByKeyResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_GetEventTypeByKeyResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_GetEventTypeByKeyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse.class, org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse.Builder.class);
  }

  private int bitField0_;
  public static final int EVENT_TYPE_FIELD_NUMBER = 1;
  private org.prism.eventsservice.grpc.events_catalog.v1.EventType eventType_;
  /**
   * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
   * @return Whether the eventType field is set.
   */
  @java.lang.Override
  public boolean hasEventType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
   * @return The eventType.
   */
  @java.lang.Override
  public org.prism.eventsservice.grpc.events_catalog.v1.EventType getEventType() {
    return eventType_ == null ? org.prism.eventsservice.grpc.events_catalog.v1.EventType.getDefaultInstance() : eventType_;
  }
  /**
   * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
   */
  @java.lang.Override
  public org.prism.eventsservice.grpc.events_catalog.v1.EventTypeOrBuilder getEventTypeOrBuilder() {
    return eventType_ == null ? org.prism.eventsservice.grpc.events_catalog.v1.EventType.getDefaultInstance() : eventType_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getEventType());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEventType());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse)) {
      return super.equals(obj);
    }
    org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse other = (org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse) obj;

    if (hasEventType() != other.hasEventType()) return false;
    if (hasEventType()) {
      if (!getEventType()
          .equals(other.getEventType())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEventType()) {
      hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEventType().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code events_catalog.v1.GetEventTypeByKeyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:events_catalog.v1.GetEventTypeByKeyResponse)
      org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_GetEventTypeByKeyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_GetEventTypeByKeyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse.class, org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse.Builder.class);
    }

    // Construct using org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetEventTypeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventType_ = null;
      if (eventTypeBuilder_ != null) {
        eventTypeBuilder_.dispose();
        eventTypeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.prism.eventsservice.grpc.events_catalog.v1.EventsCatalog.internal_static_events_catalog_v1_GetEventTypeByKeyResponse_descriptor;
    }

    @java.lang.Override
    public org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse getDefaultInstanceForType() {
      return org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse build() {
      org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse buildPartial() {
      org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse result = new org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventType_ = eventTypeBuilder_ == null
            ? eventType_
            : eventTypeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse) {
        return mergeFrom((org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse other) {
      if (other == org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse.getDefaultInstance()) return this;
      if (other.hasEventType()) {
        mergeEventType(other.getEventType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetEventTypeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.prism.eventsservice.grpc.events_catalog.v1.EventType eventType_;
    private com.google.protobuf.SingleFieldBuilder<
        org.prism.eventsservice.grpc.events_catalog.v1.EventType, org.prism.eventsservice.grpc.events_catalog.v1.EventType.Builder, org.prism.eventsservice.grpc.events_catalog.v1.EventTypeOrBuilder> eventTypeBuilder_;
    /**
     * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
     * @return Whether the eventType field is set.
     */
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
     * @return The eventType.
     */
    public org.prism.eventsservice.grpc.events_catalog.v1.EventType getEventType() {
      if (eventTypeBuilder_ == null) {
        return eventType_ == null ? org.prism.eventsservice.grpc.events_catalog.v1.EventType.getDefaultInstance() : eventType_;
      } else {
        return eventTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
     */
    public Builder setEventType(org.prism.eventsservice.grpc.events_catalog.v1.EventType value) {
      if (eventTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventType_ = value;
      } else {
        eventTypeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
     */
    public Builder setEventType(
        org.prism.eventsservice.grpc.events_catalog.v1.EventType.Builder builderForValue) {
      if (eventTypeBuilder_ == null) {
        eventType_ = builderForValue.build();
      } else {
        eventTypeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
     */
    public Builder mergeEventType(org.prism.eventsservice.grpc.events_catalog.v1.EventType value) {
      if (eventTypeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          eventType_ != null &&
          eventType_ != org.prism.eventsservice.grpc.events_catalog.v1.EventType.getDefaultInstance()) {
          getEventTypeBuilder().mergeFrom(value);
        } else {
          eventType_ = value;
        }
      } else {
        eventTypeBuilder_.mergeFrom(value);
      }
      if (eventType_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
     */
    public Builder clearEventType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      eventType_ = null;
      if (eventTypeBuilder_ != null) {
        eventTypeBuilder_.dispose();
        eventTypeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
     */
    public org.prism.eventsservice.grpc.events_catalog.v1.EventType.Builder getEventTypeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetEventTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
     */
    public org.prism.eventsservice.grpc.events_catalog.v1.EventTypeOrBuilder getEventTypeOrBuilder() {
      if (eventTypeBuilder_ != null) {
        return eventTypeBuilder_.getMessageOrBuilder();
      } else {
        return eventType_ == null ?
            org.prism.eventsservice.grpc.events_catalog.v1.EventType.getDefaultInstance() : eventType_;
      }
    }
    /**
     * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.prism.eventsservice.grpc.events_catalog.v1.EventType, org.prism.eventsservice.grpc.events_catalog.v1.EventType.Builder, org.prism.eventsservice.grpc.events_catalog.v1.EventTypeOrBuilder> 
        internalGetEventTypeFieldBuilder() {
      if (eventTypeBuilder_ == null) {
        eventTypeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.prism.eventsservice.grpc.events_catalog.v1.EventType, org.prism.eventsservice.grpc.events_catalog.v1.EventType.Builder, org.prism.eventsservice.grpc.events_catalog.v1.EventTypeOrBuilder>(
                getEventType(),
                getParentForChildren(),
                isClean());
        eventType_ = null;
      }
      return eventTypeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:events_catalog.v1.GetEventTypeByKeyResponse)
  }

  // @@protoc_insertion_point(class_scope:events_catalog.v1.GetEventTypeByKeyResponse)
  private static final org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse();
  }

  public static org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetEventTypeByKeyResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetEventTypeByKeyResponse>() {
    @java.lang.Override
    public GetEventTypeByKeyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetEventTypeByKeyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetEventTypeByKeyResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.prism.eventsservice.grpc.events_catalog.v1.GetEventTypeByKeyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

