// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events_catalog/v1/events_catalog.proto
// Protobuf Java Version: 4.33.4

package org.prism.eventsservice.grpc.events_catalog.v1;

@com.google.protobuf.Generated
public interface GetEventTypeByKeyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events_catalog.v1.GetEventTypeByKeyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
   * @return Whether the eventType field is set.
   */
  boolean hasEventType();
  /**
   * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
   * @return The eventType.
   */
  org.prism.eventsservice.grpc.events_catalog.v1.EventType getEventType();
  /**
   * <code>optional .events_catalog.v1.EventType event_type = 1;</code>
   */
  org.prism.eventsservice.grpc.events_catalog.v1.EventTypeOrBuilder getEventTypeOrBuilder();
}
