# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from stats_engine.v1 import stats_engine_pb2 as stats__engine_dot_v1_dot_stats__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stats_engine/v1/stats_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatsEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateSampleSize = channel.unary_unary(
                '/stats_engine.v1.StatsEngine/CalculateSampleSize',
                request_serializer=stats__engine_dot_v1_dot_stats__engine__pb2.CalculateSampleSizeRequest.SerializeToString,
                response_deserializer=stats__engine_dot_v1_dot_stats__engine__pb2.CalculateSampleSizeResponse.FromString,
                _registered_method=True)


class StatsEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateSampleSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateSampleSize': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateSampleSize,
                    request_deserializer=stats__engine_dot_v1_dot_stats__engine__pb2.CalculateSampleSizeRequest.FromString,
                    response_serializer=stats__engine_dot_v1_dot_stats__engine__pb2.CalculateSampleSizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stats_engine.v1.StatsEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stats_engine.v1.StatsEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatsEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateSampleSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats_engine.v1.StatsEngine/CalculateSampleSize',
            stats__engine_dot_v1_dot_stats__engine__pb2.CalculateSampleSizeRequest.SerializeToString,
            stats__engine_dot_v1_dot_stats__engine__pb2.CalculateSampleSizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
