# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats_engine/v1/stats_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stats_engine/v1/stats_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"stats_engine/v1/stats_engine.proto\x12\x0fstats_engine.v1\"\x9d\x01\n(CalculateSampleSizeAbsoluteMetricRequest\x12\x1f\n\x17\x61\x62solute_percentage_mde\x18\x01 \x01(\x01\x12\x1b\n\x13\x62\x61seline_proportion\x18\x02 \x01(\x01\x12\r\n\x05\x61lpha\x18\x03 \x01(\x01\x12\r\n\x05power\x18\x04 \x01(\x01\x12\x15\n\rvariant_count\x18\x05 \x01(\x05\"^\n)CalculateSampleSizeAbsoluteMetricResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x13\n\x0bper_variant\x18\x02 \x03(\x05\x12\r\n\x05split\x18\x03 \x03(\x01\x32\xaa\x01\n\x0bStatsEngine\x12\x9a\x01\n!CalculateSampleSizeAbsoluteMetric\x12\x39.stats_engine.v1.CalculateSampleSizeAbsoluteMetricRequest\x1a:.stats_engine.v1.CalculateSampleSizeAbsoluteMetricResponseBAZ?experimentation-service/internal/grpc/generated/v1;stats_engineb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_engine.v1.stats_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?experimentation-service/internal/grpc/generated/v1;stats_engine'
  _globals['_CALCULATESAMPLESIZEABSOLUTEMETRICREQUEST']._serialized_start=56
  _globals['_CALCULATESAMPLESIZEABSOLUTEMETRICREQUEST']._serialized_end=213
  _globals['_CALCULATESAMPLESIZEABSOLUTEMETRICRESPONSE']._serialized_start=215
  _globals['_CALCULATESAMPLESIZEABSOLUTEMETRICRESPONSE']._serialized_end=309
  _globals['_STATSENGINE']._serialized_start=312
  _globals['_STATSENGINE']._serialized_end=482
# @@protoc_insertion_point(module_scope)
