openapi: 3.0.3
info:
  title: Experimentation Service API
servers:
  - url: http://localhost:8081/api
tags:
  - name: Event Catalog
  - name: Metric Catalog

paths:
  /events-catalog:
    get:
      tags:
        - Event Catalog
      summary: List or search event types
      operationId: getEventTypes
      parameters:
        - name: search
          in: query
          required: false
          description: Optional search term to find eventTypes by name
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EventType"
        "500":
          $ref: "../problems.yaml#/responses/InternalServerError"

    post:
      tags:
        - Event Catalog
      summary: Create an event type
      operationId: createEventType
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEventTypeRequest"
            example:
              name: "Purchase Completed"
              event_key: "purchase_completed"
              description: 'Fired when a user completes a purchase. This example maps to the object: { "order_total": 100.0, "currency": "USD" }'
              fields:
                - name: "Order Total"
                  field_key: "order_total"
                  data_type: "float"
                - name: "Currency"
                  field_key: "currency"
                  data_type: "string"
      responses:
        "201":
          description: Event type created successfully
        "400":
          $ref: "../problems.yaml#/responses/BadRequest"
        "422":
          $ref: "../problems.yaml#/responses/ValidationError"
        "500":
          $ref: "../problems.yaml#/responses/InternalServerError"

  /events-catalog/{eventTypeId}:
    get:
      tags:
        - Event Catalog
      summary: Get an event type by ID
      operationId: getEventType
      parameters:
        - $ref: "#/components/parameters/eventTypeId"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventType"
        "400":
          $ref: "../problems.yaml#/responses/BadRequest"
        "404":
          description: Event type not found
          content:
            application/problem+json:
              schema:
                $ref: "../problems.yaml#/schemas/ProblemDetail"
              example:
                title: "Not Found"
                status: 404
                detail: "Event type not found"
        "500":
          $ref: "../problems.yaml#/responses/InternalServerError"

    delete:
      tags:
        - Event Catalog
      summary: Delete an event type
      description: Deletes the event type and all associated fields.
      operationId: deleteEventType
      parameters:
        - $ref: "#/components/parameters/eventTypeId"
      responses:
        "204":
          description: Event type deleted successfully
        "400":
          $ref: "../problems.yaml#/responses/BadRequest"
        "500":
          $ref: "../problems.yaml#/responses/InternalServerError"

  /events-catalog/event-key-available:
    get:
      tags:
        - Event Catalog
      summary: Check if an event key is available
      operationId: isEventKeyAvailableForExperiment
      parameters:
        - name: eventKey
          in: query
          required: true
          schema:
            type: string
          example: "purchase_completed"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean
              example:
                available: true
        "400":
          $ref: "../problems.yaml#/responses/BadRequest"
        "500":
          $ref: "../problems.yaml#/responses/InternalServerError"

  /events-catalog/key/{eventKey}:
    get:
      tags:
        - Event Catalog
      summary: Get an event type by key
      operationId: getEventTypeByKey
      parameters:
        - $ref: "#/components/parameters/eventKey"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventType"
        "400":
          $ref: "../problems.yaml#/responses/BadRequest"
        "404":
          description: Event type not found
          content:
            application/problem+json:
              schema:
                $ref: "../problems.yaml#/schemas/ProblemDetail"
              example:
                title: "Not Found"
                status: 404
                detail: "Event type not found"
        "500":
          $ref: "../problems.yaml#/responses/InternalServerError"

  /events-catalog/key/{eventKey}/usage:
    get:
      tags:
        - Event Catalog
      summary: Get TimeSeries data for event over period
      description: returns event count for over a period of time in a time series format. Aggregations are performed server side based on the graphScale parameter.
      operationId: getEventUsageOverPeriod
      parameters:
        - $ref: "#/components/parameters/eventKey"
        - $ref: "#/components/parameters/graphScale"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TimeScaleDataPoint"
        "400":
          $ref: "../problems.yaml#/responses/BadRequest"
        "500":
          $ref: "../problems.yaml#/responses/InternalServerError"

  /events-catalog/key/{eventKey}/stats:
    get:
      tags:
        - Event Catalog
      summary: Get live event statistics
      operationId: getLiveEventStats
      parameters:
        - $ref: "#/components/parameters/eventKey"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LiveEventStatistics"
        "400":
          $ref: "../problems.yaml#/responses/BadRequest"
        "500":
          $ref: "../problems.yaml#/responses/InternalServerError"

  /events-catalog/{eventTypeId}/field-key-available:
    get:
      tags:
        - Event Catalog
      summary: Check if a field key is available
      operationId: isFieldKeyAvailableForExperiment
      parameters:
        - $ref: "#/components/parameters/eventTypeId"
        - name: fieldKey
          in: query
          required: true
          schema:
            type: string
          example: "order_total"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean
              example:
                available: true
        "400":
          $ref: "../problems.yaml#/responses/BadRequest"
        "500":
          $ref: "../problems.yaml#/responses/InternalServerError"

  /metrics-catalog/:
    post:
      tags:
        - Metric Catalog
      summary: Create Metric
      operationId: createMetric
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMetricRequest"
      responses:
        "201":
          description: Event type created successfully
        "400":
          $ref: "../problems.yaml#/responses/BadRequest"
        "422":
          $ref: "../problems.yaml#/responses/ValidationError"
        "500":
          $ref: "../problems.yaml#/responses/InternalServerError"

components:
  parameters:
    eventTypeId:
      name: eventTypeId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      example: "989618ba-efce-4854-be23-ede08787a6d1"

    eventKey:
      name: eventKey
      in: path
      required: true
      schema:
        type: string
        pattern: "^[a-zA-Z][a-zA-Z0-9_-]*$"
      example: "purchase_completed"

    graphScale:
      name: graphScale
      in: query
      required: true
      schema:
        $ref: "#/components/schemas/GraphTimeScale"
      example: "hour"

  schemas:
    CreateEventTypeRequest:
      type: object
      required:
        - name
        - event_key
        - fields
      properties:
        name:
          type: string
          maxLength: 100
          example: "Purchase Completed"
        event_key:
          type: string
          maxLength: 50
          pattern: "^[a-zA-Z][a-zA-Z0-9_-]*$"
          example: "purchase_completed"
        description:
          type: string
          example: "Fired when a user completes a purchase"
        fields:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/EventFieldRequest"

    EventFieldRequest:
      type: object
      required:
        - name
        - field_key
        - data_type
      properties:
        name:
          type: string
          maxLength: 100
          example: "Order Total"
        field_key:
          type: string
          maxLength: 50
          pattern: "^[a-zA-Z][a-zA-Z0-9_-]*$"
          example: "order_total"
        data_type:
          $ref: "#/components/schemas/DataType"

    EventType:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "989618ba-efce-4854-be23-ede08787a6d1"
        name:
          type: string
        event_key:
          type: string
        version:
          type: integer
        description:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        fields:
          type: array
          items:
            $ref: "#/components/schemas/EventField"

    EventField:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "250bf027-d8d9-436d-ba21-57f46162c1b0"
        name:
          type: string
        field_key:
          type: string
        data_type:
          $ref: "#/components/schemas/DataType"

    DataType:
      type: string
      enum:
        - string
        - int
        - float
        - boolean
        - timestamp

    GraphTimeScale:
      type: string
      enum:
        - ten_minute
        - half_hour
        - hour
        - day
        - week
        - month

    TimeScaleDataPoint:
      type: object
      properties:
        time:
          type: string
          format: date-time
        value:
          type: integer
          format: int

    LiveEventStatistics:
      type: object
      properties:
        missingRates:
          type: object
          additionalProperties:
            type: integer
            format: int
        totalEventsPast24Hours:
          type: integer
          format: int
        totalEventsPast7Days:
          type: integer
          format: int
        lastReceivedTime:
          type: string
          format: date-time

    CreateMetricRequest:
      type: object
      required:
        - name
        - metric_key
        - metric_type
        - analysis_unit
        - components
      properties:
        name:
          type: string
          maxLength: 255
          example: "Average Order Value"
        description:
          type: string
          example: "Average value of completed orders"
        metric_key:
          type: string
          maxLength: 50
          example: "avg_order_value"
        metric_type:
          $ref: "#/components/schemas/MetricType"
        analysis_unit:
          $ref: "#/components/schemas/AnalysisUnit"
        components:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/CreateMetricRequestComponent"

    CreateMetricRequestComponent:
      type: object
      required:
        - role
        - event_type_id
        - event_field_id
        - aggregation_operation
      properties:
        role:
          $ref: "#/components/schemas/ComponentRole"
        event_type_id:
          type: string
          format: uuid
          example: "989618ba-efce-4854-be23-ede08787a6d1"
        event_field_id:
          type: string
          format: uuid
          example: "250bf027-d8d9-436d-ba21-57f46162c1b0"
        aggregation_operation:
          $ref: "#/components/schemas/AggregationOperation"

    MetricType:
      type: string
      enum:
        - simple
        - ratio

    AnalysisUnit:
      type: string
      enum:
        - user

    ComponentRole:
      type: string
      enum:
        - base_event
        - numerator
        - denominator

    AggregationOperation:
      type: string
      enum:
        - COUNT
        - SUM
        - AVG
        - MIN
        - MAX
        - COUNT_DISTINCT
