name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  experimentation-service-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Run experimentation-service tests
        run: cd services/experimentation-service && go test ./...

  assignment-service-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Run assignment-service tests
        run: cd services/assignment-service && go test ./...

  clickhouse-writer-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Run clickhouse-writer tests
        run: cd services/clickhouse-writer && go test ./...

  events-service-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run events-service verify
        run: cd services/events-service && ./mvnw --batch-mode verify

  openfeature-provider-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install dependencies
        run: cd openfeature-provider-react && npm install

      - name: Run Jest tests
        run: cd openfeature-provider-react && npm test
